name: urecycle_app
description: "A CNN-based mobile application that monitors student waste at University of Cabuyao."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.2
  fl_chart: ^0.68.0
  shared_preferences: ^2.3.1
  camera: ^0.10.0
  image_picker: ^1.1.2
  image: ^3.0.0
  tflite_flutter_helper_plus: ^0.0.2
  tflite_flutter: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.11.0

flutter_launcher_icons:
  android: true
  ios: true
  android_image_path: "assets/icon/icon.png"
  ios_image_path: "assets/icon/icon.png"
  min_sdk_android: 16

flutter:
  uses-material-design: true
  assets:
    - assets/icon/logo.png
    - assets/images/SGD_12.png
    - assets/images/MNV.jpg
    - assets/model.tflite
    - assets/model.txt