name: urecycle_app
description: "A CNN-based mobile application that monitors student waste at University of Cabuyao."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.2
  fl_chart: ^0.69.0
  shared_preferences: ^2.3.1
  camera: ^0.10.0
  image_picker: ^1.1.2
  image: ^3.0.0
  tflite_flutter: ^0.11.0
  mobile_scanner: ^5.2.2
  provider: ^6.1.2
  firebase_messaging: ^14.7.10
  firebase_core: ^2.24.2
  intl: ^0.19.0
  flutter_local_notifications: ^17.2.2
  qr_flutter: ^4.1.0
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  path_provider: ^2.1.4
  google_mlkit_image_labeling: ^0.13.0
  path: ^1.9.0
  pytorch_lite: ^2.0.5
  tflite_flutter_helper_plus: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.11.0
  build_runner: ^2.4.11
  hive_generator: ^2.0.1

flutter_launcher_icons:
  android: true
  ios: true
  android_image_path: "assets/icon/icon.png"
  ios_image_path: "assets/icon/icon.png"
  min_sdk_android: 16

flutter:
  uses-material-design: true
  assets:
    - assets/icon/logo.png
    - assets/images/SGD_12.png
    - assets/images/MNV.jpg
    - assets/models/model.tflite
    - assets/labels/model.txt
    - assets/labels/classes.txt
    - assets/models/1.tflite
    - assets/models/2.tflite
    - assets/models/mobilenetv3.tflite
    - assets/labels/mobilenetv3.txt
    - assets/models/v3-small_224_1.0_uint8.tflite
    - assets/models/mobilenetv2_uint8.tflite
    - assets/models/mobilenetv2_uint8_with_metadata.tflite
    - assets/models/efficientnet_lite0_quantized.pt